name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose
    - name: Testing mp4decrypt::mp4decrypt
      run: cargo run --example decrypt
    - name: Testing mp4decrypt::mp4split
      run: cargo run --example split
